name: DtDE
favicon: null
layout_spectrum: 0.3854068706277758
typography_spectrum: 0.5372812643181533
title: Dancetheatre David Earle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.774132079211995
  lightness: 0.7203206021804363
  saturation: 0.3746316400356591
  rhythmicContrast: 0.6052530228625983
purpose: []
